version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/dev/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    mode: 777
    owner: root
    group: root

hooks:
  ApplicationStart:
    - location: appStart.sh
      timeout: 60
      runas: root