version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/dev/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    mode: 777
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: appStart.sh
      timeout: 60
      runas: ec2-user