name: ci-cd

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean bootjar

      - name: Test with Gradle
        run: ./gradlew test

      - name: Make Directory
        run: mkdir deploy

      - name: Copy Jar
        run: Copy-Item -Path ./build/libs/*.jar -Destination ./deploy
        shell: pwsh

      - name: Copy appspec.yml
        run: Copy-Item -Path appspec.yml -Destination ./deploy
        shell: pwsh

      - name: Copy script
        run: Copy-Item -Path ./scripts/*.sh -Destination ./deploy
        shell: pwsh

      - name: Make zip file
        run: Compress-Archive -Path ./deploy -DestinationPath ./build/libs/ci-cd-test.zip
        shell: pwsh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./build/libs/ci-cd-test.zip s3://ci-cd-test-202403281047/ci-cd-test.zip

      - name: Deploy
        run: aws deploy create-deployment 
          --application-name ci-cd
          --deployment-group-name ci-cd
          --file-exists-behavior OVERWRITE
          --s3-location bucket=ci-cd-test-202403281047,bundleType=zip,key=ci-cd-test.zip
          --region ap-northeast-2